export const ACTION_BEGIN = "ACTION_BEGIN";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const ACTION_FAILURE = "ACTION_FAILURE";
export const ACTION_SET_PAGE = "ACTION_SET_PAGE";
export const ACTION_SET_MODE = "ACTION_SET_MODE";
export const ACTION_SET_FILTERS = "ACTION_SET_FILTERS";
export const ACTION_SET_SEARCH_VALUE = "ACTION_SET_SEARCH_VALUE";
